version: 2
formats: all
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
python:
  install:
    - requirements: doc/requirements.txt
sphinx:
  # Path to your Sphinx configuration file.
  configuration: doc/conf.py
