name: Jupyter Notebooks CI
on: [push, pull_request]
jobs:
  Check-Notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: set up mamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-examples.yml
          generate-run-shell: true
          cache-environment: true
          cache-downloads: true
      - name: Install tobac
        run: |
          pip install .
      - name: Find all notebook files
        run: |
          find . -type f -name '*.ipynb' > nbfiles.txt
          cat nbfiles.txt
      - name: Execute all notebook files
        run: |
          while IFS= read -r nbpath; do
            jupyter nbconvert --inplace --ClearMetadataPreprocessor.enabled=True --clear-output $nbpath
            jupyter nbconvert --to notebook --inplace --execute $nbpath
          done < nbfiles.txt